CREATE USER looker WITH ENCRYPTED PASSWORD 'some_password_here';
CREATE USER looker WITH ENCRYPTED PASSWORD 'Xje29eHQrHozPbnuk';
GRANT CONNECT ON DATABASE wikipetiadw to looker;
\ c database_name
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO looker;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO looker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON tables TO looker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON sequences TO looker;
CREATE SCHEMA looker_scratch AUTHORIZATION looker;